/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package bank;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.11.0)", date = "2018-07-02")
public class AccountInfo implements org.apache.thrift.TBase<AccountInfo, AccountInfo._Fields>, java.io.Serializable, Cloneable, Comparable<AccountInfo> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("AccountInfo");

  private static final org.apache.thrift.protocol.TField BALANCE_FIELD_DESC = new org.apache.thrift.protocol.TField("balance", org.apache.thrift.protocol.TType.DOUBLE, (short)1);
  private static final org.apache.thrift.protocol.TField GUID_FIELD_DESC = new org.apache.thrift.protocol.TField("guid", org.apache.thrift.protocol.TType.I32, (short)2);
  private static final org.apache.thrift.protocol.TField IS_PREMIUM_FIELD_DESC = new org.apache.thrift.protocol.TField("isPremium", org.apache.thrift.protocol.TType.BOOL, (short)3);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new AccountInfoStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new AccountInfoTupleSchemeFactory();

  public double balance; // required
  public int guid; // required
  public boolean isPremium; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    BALANCE((short)1, "balance"),
    GUID((short)2, "guid"),
    IS_PREMIUM((short)3, "isPremium");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // BALANCE
          return BALANCE;
        case 2: // GUID
          return GUID;
        case 3: // IS_PREMIUM
          return IS_PREMIUM;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __BALANCE_ISSET_ID = 0;
  private static final int __GUID_ISSET_ID = 1;
  private static final int __ISPREMIUM_ISSET_ID = 2;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.BALANCE, new org.apache.thrift.meta_data.FieldMetaData("balance", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.DOUBLE)));
    tmpMap.put(_Fields.GUID, new org.apache.thrift.meta_data.FieldMetaData("guid", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.IS_PREMIUM, new org.apache.thrift.meta_data.FieldMetaData("isPremium", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(AccountInfo.class, metaDataMap);
  }

  public AccountInfo() {
  }

  public AccountInfo(
    double balance,
    int guid,
    boolean isPremium)
  {
    this();
    this.balance = balance;
    setBalanceIsSet(true);
    this.guid = guid;
    setGuidIsSet(true);
    this.isPremium = isPremium;
    setIsPremiumIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public AccountInfo(AccountInfo other) {
    __isset_bitfield = other.__isset_bitfield;
    this.balance = other.balance;
    this.guid = other.guid;
    this.isPremium = other.isPremium;
  }

  public AccountInfo deepCopy() {
    return new AccountInfo(this);
  }

  @Override
  public void clear() {
    setBalanceIsSet(false);
    this.balance = 0.0;
    setGuidIsSet(false);
    this.guid = 0;
    setIsPremiumIsSet(false);
    this.isPremium = false;
  }

  public double getBalance() {
    return this.balance;
  }

  public AccountInfo setBalance(double balance) {
    this.balance = balance;
    setBalanceIsSet(true);
    return this;
  }

  public void unsetBalance() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __BALANCE_ISSET_ID);
  }

  /** Returns true if field balance is set (has been assigned a value) and false otherwise */
  public boolean isSetBalance() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __BALANCE_ISSET_ID);
  }

  public void setBalanceIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __BALANCE_ISSET_ID, value);
  }

  public int getGuid() {
    return this.guid;
  }

  public AccountInfo setGuid(int guid) {
    this.guid = guid;
    setGuidIsSet(true);
    return this;
  }

  public void unsetGuid() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __GUID_ISSET_ID);
  }

  /** Returns true if field guid is set (has been assigned a value) and false otherwise */
  public boolean isSetGuid() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __GUID_ISSET_ID);
  }

  public void setGuidIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __GUID_ISSET_ID, value);
  }

  public boolean isIsPremium() {
    return this.isPremium;
  }

  public AccountInfo setIsPremium(boolean isPremium) {
    this.isPremium = isPremium;
    setIsPremiumIsSet(true);
    return this;
  }

  public void unsetIsPremium() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __ISPREMIUM_ISSET_ID);
  }

  /** Returns true if field isPremium is set (has been assigned a value) and false otherwise */
  public boolean isSetIsPremium() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __ISPREMIUM_ISSET_ID);
  }

  public void setIsPremiumIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __ISPREMIUM_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, java.lang.Object value) {
    switch (field) {
    case BALANCE:
      if (value == null) {
        unsetBalance();
      } else {
        setBalance((java.lang.Double)value);
      }
      break;

    case GUID:
      if (value == null) {
        unsetGuid();
      } else {
        setGuid((java.lang.Integer)value);
      }
      break;

    case IS_PREMIUM:
      if (value == null) {
        unsetIsPremium();
      } else {
        setIsPremium((java.lang.Boolean)value);
      }
      break;

    }
  }

  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case BALANCE:
      return getBalance();

    case GUID:
      return getGuid();

    case IS_PREMIUM:
      return isIsPremium();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case BALANCE:
      return isSetBalance();
    case GUID:
      return isSetGuid();
    case IS_PREMIUM:
      return isSetIsPremium();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof AccountInfo)
      return this.equals((AccountInfo)that);
    return false;
  }

  public boolean equals(AccountInfo that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_balance = true;
    boolean that_present_balance = true;
    if (this_present_balance || that_present_balance) {
      if (!(this_present_balance && that_present_balance))
        return false;
      if (this.balance != that.balance)
        return false;
    }

    boolean this_present_guid = true;
    boolean that_present_guid = true;
    if (this_present_guid || that_present_guid) {
      if (!(this_present_guid && that_present_guid))
        return false;
      if (this.guid != that.guid)
        return false;
    }

    boolean this_present_isPremium = true;
    boolean that_present_isPremium = true;
    if (this_present_isPremium || that_present_isPremium) {
      if (!(this_present_isPremium && that_present_isPremium))
        return false;
      if (this.isPremium != that.isPremium)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(balance);

    hashCode = hashCode * 8191 + guid;

    hashCode = hashCode * 8191 + ((isPremium) ? 131071 : 524287);

    return hashCode;
  }

  @Override
  public int compareTo(AccountInfo other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetBalance()).compareTo(other.isSetBalance());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetBalance()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.balance, other.balance);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetGuid()).compareTo(other.isSetGuid());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetGuid()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.guid, other.guid);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetIsPremium()).compareTo(other.isSetIsPremium());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetIsPremium()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.isPremium, other.isPremium);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("AccountInfo(");
    boolean first = true;

    sb.append("balance:");
    sb.append(this.balance);
    first = false;
    if (!first) sb.append(", ");
    sb.append("guid:");
    sb.append(this.guid);
    first = false;
    if (!first) sb.append(", ");
    sb.append("isPremium:");
    sb.append(this.isPremium);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class AccountInfoStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public AccountInfoStandardScheme getScheme() {
      return new AccountInfoStandardScheme();
    }
  }

  private static class AccountInfoStandardScheme extends org.apache.thrift.scheme.StandardScheme<AccountInfo> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, AccountInfo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // BALANCE
            if (schemeField.type == org.apache.thrift.protocol.TType.DOUBLE) {
              struct.balance = iprot.readDouble();
              struct.setBalanceIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // GUID
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.guid = iprot.readI32();
              struct.setGuidIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // IS_PREMIUM
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.isPremium = iprot.readBool();
              struct.setIsPremiumIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, AccountInfo struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(BALANCE_FIELD_DESC);
      oprot.writeDouble(struct.balance);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(GUID_FIELD_DESC);
      oprot.writeI32(struct.guid);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(IS_PREMIUM_FIELD_DESC);
      oprot.writeBool(struct.isPremium);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class AccountInfoTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public AccountInfoTupleScheme getScheme() {
      return new AccountInfoTupleScheme();
    }
  }

  private static class AccountInfoTupleScheme extends org.apache.thrift.scheme.TupleScheme<AccountInfo> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, AccountInfo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetBalance()) {
        optionals.set(0);
      }
      if (struct.isSetGuid()) {
        optionals.set(1);
      }
      if (struct.isSetIsPremium()) {
        optionals.set(2);
      }
      oprot.writeBitSet(optionals, 3);
      if (struct.isSetBalance()) {
        oprot.writeDouble(struct.balance);
      }
      if (struct.isSetGuid()) {
        oprot.writeI32(struct.guid);
      }
      if (struct.isSetIsPremium()) {
        oprot.writeBool(struct.isPremium);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, AccountInfo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(3);
      if (incoming.get(0)) {
        struct.balance = iprot.readDouble();
        struct.setBalanceIsSet(true);
      }
      if (incoming.get(1)) {
        struct.guid = iprot.readI32();
        struct.setGuidIsSet(true);
      }
      if (incoming.get(2)) {
        struct.isPremium = iprot.readBool();
        struct.setIsPremiumIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

