/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package bank;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.11.0)", date = "2018-07-01")
public class LoanParameters implements org.apache.thrift.TBase<LoanParameters, LoanParameters._Fields>, java.io.Serializable, Cloneable, Comparable<LoanParameters> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("LoanParameters");

  private static final org.apache.thrift.protocol.TField CURRENCY_FIELD_DESC = new org.apache.thrift.protocol.TField("currency", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField MONEY_AMOUNT_FIELD_DESC = new org.apache.thrift.protocol.TField("moneyAmount", org.apache.thrift.protocol.TType.DOUBLE, (short)2);
  private static final org.apache.thrift.protocol.TField START_DATE_FIELD_DESC = new org.apache.thrift.protocol.TField("startDate", org.apache.thrift.protocol.TType.STRING, (short)3);
  private static final org.apache.thrift.protocol.TField CLOSE_DATE_FIELD_DESC = new org.apache.thrift.protocol.TField("closeDate", org.apache.thrift.protocol.TType.STRING, (short)4);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new LoanParametersStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new LoanParametersTupleSchemeFactory();

  public java.lang.String currency; // required
  public double moneyAmount; // required
  public java.lang.String startDate; // required
  public java.lang.String closeDate; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    CURRENCY((short)1, "currency"),
    MONEY_AMOUNT((short)2, "moneyAmount"),
    START_DATE((short)3, "startDate"),
    CLOSE_DATE((short)4, "closeDate");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // CURRENCY
          return CURRENCY;
        case 2: // MONEY_AMOUNT
          return MONEY_AMOUNT;
        case 3: // START_DATE
          return START_DATE;
        case 4: // CLOSE_DATE
          return CLOSE_DATE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __MONEYAMOUNT_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.CURRENCY, new org.apache.thrift.meta_data.FieldMetaData("currency", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING        , "Currency")));
    tmpMap.put(_Fields.MONEY_AMOUNT, new org.apache.thrift.meta_data.FieldMetaData("moneyAmount", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.DOUBLE)));
    tmpMap.put(_Fields.START_DATE, new org.apache.thrift.meta_data.FieldMetaData("startDate", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING        , "Date")));
    tmpMap.put(_Fields.CLOSE_DATE, new org.apache.thrift.meta_data.FieldMetaData("closeDate", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING        , "Date")));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(LoanParameters.class, metaDataMap);
  }

  public LoanParameters() {
  }

  public LoanParameters(
    java.lang.String currency,
    double moneyAmount,
    java.lang.String startDate,
    java.lang.String closeDate)
  {
    this();
    this.currency = currency;
    this.moneyAmount = moneyAmount;
    setMoneyAmountIsSet(true);
    this.startDate = startDate;
    this.closeDate = closeDate;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public LoanParameters(LoanParameters other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetCurrency()) {
      this.currency = other.currency;
    }
    this.moneyAmount = other.moneyAmount;
    if (other.isSetStartDate()) {
      this.startDate = other.startDate;
    }
    if (other.isSetCloseDate()) {
      this.closeDate = other.closeDate;
    }
  }

  public LoanParameters deepCopy() {
    return new LoanParameters(this);
  }

  @Override
  public void clear() {
    this.currency = null;
    setMoneyAmountIsSet(false);
    this.moneyAmount = 0.0;
    this.startDate = null;
    this.closeDate = null;
  }

  public java.lang.String getCurrency() {
    return this.currency;
  }

  public LoanParameters setCurrency(java.lang.String currency) {
    this.currency = currency;
    return this;
  }

  public void unsetCurrency() {
    this.currency = null;
  }

  /** Returns true if field currency is set (has been assigned a value) and false otherwise */
  public boolean isSetCurrency() {
    return this.currency != null;
  }

  public void setCurrencyIsSet(boolean value) {
    if (!value) {
      this.currency = null;
    }
  }

  public double getMoneyAmount() {
    return this.moneyAmount;
  }

  public LoanParameters setMoneyAmount(double moneyAmount) {
    this.moneyAmount = moneyAmount;
    setMoneyAmountIsSet(true);
    return this;
  }

  public void unsetMoneyAmount() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __MONEYAMOUNT_ISSET_ID);
  }

  /** Returns true if field moneyAmount is set (has been assigned a value) and false otherwise */
  public boolean isSetMoneyAmount() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __MONEYAMOUNT_ISSET_ID);
  }

  public void setMoneyAmountIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __MONEYAMOUNT_ISSET_ID, value);
  }

  public java.lang.String getStartDate() {
    return this.startDate;
  }

  public LoanParameters setStartDate(java.lang.String startDate) {
    this.startDate = startDate;
    return this;
  }

  public void unsetStartDate() {
    this.startDate = null;
  }

  /** Returns true if field startDate is set (has been assigned a value) and false otherwise */
  public boolean isSetStartDate() {
    return this.startDate != null;
  }

  public void setStartDateIsSet(boolean value) {
    if (!value) {
      this.startDate = null;
    }
  }

  public java.lang.String getCloseDate() {
    return this.closeDate;
  }

  public LoanParameters setCloseDate(java.lang.String closeDate) {
    this.closeDate = closeDate;
    return this;
  }

  public void unsetCloseDate() {
    this.closeDate = null;
  }

  /** Returns true if field closeDate is set (has been assigned a value) and false otherwise */
  public boolean isSetCloseDate() {
    return this.closeDate != null;
  }

  public void setCloseDateIsSet(boolean value) {
    if (!value) {
      this.closeDate = null;
    }
  }

  public void setFieldValue(_Fields field, java.lang.Object value) {
    switch (field) {
    case CURRENCY:
      if (value == null) {
        unsetCurrency();
      } else {
        setCurrency((java.lang.String)value);
      }
      break;

    case MONEY_AMOUNT:
      if (value == null) {
        unsetMoneyAmount();
      } else {
        setMoneyAmount((java.lang.Double)value);
      }
      break;

    case START_DATE:
      if (value == null) {
        unsetStartDate();
      } else {
        setStartDate((java.lang.String)value);
      }
      break;

    case CLOSE_DATE:
      if (value == null) {
        unsetCloseDate();
      } else {
        setCloseDate((java.lang.String)value);
      }
      break;

    }
  }

  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case CURRENCY:
      return getCurrency();

    case MONEY_AMOUNT:
      return getMoneyAmount();

    case START_DATE:
      return getStartDate();

    case CLOSE_DATE:
      return getCloseDate();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case CURRENCY:
      return isSetCurrency();
    case MONEY_AMOUNT:
      return isSetMoneyAmount();
    case START_DATE:
      return isSetStartDate();
    case CLOSE_DATE:
      return isSetCloseDate();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof LoanParameters)
      return this.equals((LoanParameters)that);
    return false;
  }

  public boolean equals(LoanParameters that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_currency = true && this.isSetCurrency();
    boolean that_present_currency = true && that.isSetCurrency();
    if (this_present_currency || that_present_currency) {
      if (!(this_present_currency && that_present_currency))
        return false;
      if (!this.currency.equals(that.currency))
        return false;
    }

    boolean this_present_moneyAmount = true;
    boolean that_present_moneyAmount = true;
    if (this_present_moneyAmount || that_present_moneyAmount) {
      if (!(this_present_moneyAmount && that_present_moneyAmount))
        return false;
      if (this.moneyAmount != that.moneyAmount)
        return false;
    }

    boolean this_present_startDate = true && this.isSetStartDate();
    boolean that_present_startDate = true && that.isSetStartDate();
    if (this_present_startDate || that_present_startDate) {
      if (!(this_present_startDate && that_present_startDate))
        return false;
      if (!this.startDate.equals(that.startDate))
        return false;
    }

    boolean this_present_closeDate = true && this.isSetCloseDate();
    boolean that_present_closeDate = true && that.isSetCloseDate();
    if (this_present_closeDate || that_present_closeDate) {
      if (!(this_present_closeDate && that_present_closeDate))
        return false;
      if (!this.closeDate.equals(that.closeDate))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetCurrency()) ? 131071 : 524287);
    if (isSetCurrency())
      hashCode = hashCode * 8191 + currency.hashCode();

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(moneyAmount);

    hashCode = hashCode * 8191 + ((isSetStartDate()) ? 131071 : 524287);
    if (isSetStartDate())
      hashCode = hashCode * 8191 + startDate.hashCode();

    hashCode = hashCode * 8191 + ((isSetCloseDate()) ? 131071 : 524287);
    if (isSetCloseDate())
      hashCode = hashCode * 8191 + closeDate.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(LoanParameters other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetCurrency()).compareTo(other.isSetCurrency());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCurrency()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.currency, other.currency);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetMoneyAmount()).compareTo(other.isSetMoneyAmount());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMoneyAmount()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.moneyAmount, other.moneyAmount);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetStartDate()).compareTo(other.isSetStartDate());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetStartDate()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.startDate, other.startDate);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetCloseDate()).compareTo(other.isSetCloseDate());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCloseDate()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.closeDate, other.closeDate);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("LoanParameters(");
    boolean first = true;

    sb.append("currency:");
    if (this.currency == null) {
      sb.append("null");
    } else {
      sb.append(this.currency);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("moneyAmount:");
    sb.append(this.moneyAmount);
    first = false;
    if (!first) sb.append(", ");
    sb.append("startDate:");
    if (this.startDate == null) {
      sb.append("null");
    } else {
      sb.append(this.startDate);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("closeDate:");
    if (this.closeDate == null) {
      sb.append("null");
    } else {
      sb.append(this.closeDate);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class LoanParametersStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public LoanParametersStandardScheme getScheme() {
      return new LoanParametersStandardScheme();
    }
  }

  private static class LoanParametersStandardScheme extends org.apache.thrift.scheme.StandardScheme<LoanParameters> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, LoanParameters struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // CURRENCY
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.currency = iprot.readString();
              struct.setCurrencyIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // MONEY_AMOUNT
            if (schemeField.type == org.apache.thrift.protocol.TType.DOUBLE) {
              struct.moneyAmount = iprot.readDouble();
              struct.setMoneyAmountIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // START_DATE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.startDate = iprot.readString();
              struct.setStartDateIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // CLOSE_DATE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.closeDate = iprot.readString();
              struct.setCloseDateIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, LoanParameters struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.currency != null) {
        oprot.writeFieldBegin(CURRENCY_FIELD_DESC);
        oprot.writeString(struct.currency);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(MONEY_AMOUNT_FIELD_DESC);
      oprot.writeDouble(struct.moneyAmount);
      oprot.writeFieldEnd();
      if (struct.startDate != null) {
        oprot.writeFieldBegin(START_DATE_FIELD_DESC);
        oprot.writeString(struct.startDate);
        oprot.writeFieldEnd();
      }
      if (struct.closeDate != null) {
        oprot.writeFieldBegin(CLOSE_DATE_FIELD_DESC);
        oprot.writeString(struct.closeDate);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class LoanParametersTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public LoanParametersTupleScheme getScheme() {
      return new LoanParametersTupleScheme();
    }
  }

  private static class LoanParametersTupleScheme extends org.apache.thrift.scheme.TupleScheme<LoanParameters> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, LoanParameters struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetCurrency()) {
        optionals.set(0);
      }
      if (struct.isSetMoneyAmount()) {
        optionals.set(1);
      }
      if (struct.isSetStartDate()) {
        optionals.set(2);
      }
      if (struct.isSetCloseDate()) {
        optionals.set(3);
      }
      oprot.writeBitSet(optionals, 4);
      if (struct.isSetCurrency()) {
        oprot.writeString(struct.currency);
      }
      if (struct.isSetMoneyAmount()) {
        oprot.writeDouble(struct.moneyAmount);
      }
      if (struct.isSetStartDate()) {
        oprot.writeString(struct.startDate);
      }
      if (struct.isSetCloseDate()) {
        oprot.writeString(struct.closeDate);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, LoanParameters struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(4);
      if (incoming.get(0)) {
        struct.currency = iprot.readString();
        struct.setCurrencyIsSet(true);
      }
      if (incoming.get(1)) {
        struct.moneyAmount = iprot.readDouble();
        struct.setMoneyAmountIsSet(true);
      }
      if (incoming.get(2)) {
        struct.startDate = iprot.readString();
        struct.setStartDateIsSet(true);
      }
      if (incoming.get(3)) {
        struct.closeDate = iprot.readString();
        struct.setCloseDateIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

