/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package bank;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.11.0)", date = "2018-07-02")
public class LoanCosts implements org.apache.thrift.TBase<LoanCosts, LoanCosts._Fields>, java.io.Serializable, Cloneable, Comparable<LoanCosts> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("LoanCosts");

  private static final org.apache.thrift.protocol.TField CURRENCY_COST_FIELD_DESC = new org.apache.thrift.protocol.TField("currencyCost", org.apache.thrift.protocol.TType.DOUBLE, (short)1);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new LoanCostsStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new LoanCostsTupleSchemeFactory();

  public double currencyCost; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    CURRENCY_COST((short)1, "currencyCost");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // CURRENCY_COST
          return CURRENCY_COST;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __CURRENCYCOST_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.CURRENCY_COST, new org.apache.thrift.meta_data.FieldMetaData("currencyCost", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.DOUBLE)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(LoanCosts.class, metaDataMap);
  }

  public LoanCosts() {
  }

  public LoanCosts(
    double currencyCost)
  {
    this();
    this.currencyCost = currencyCost;
    setCurrencyCostIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public LoanCosts(LoanCosts other) {
    __isset_bitfield = other.__isset_bitfield;
    this.currencyCost = other.currencyCost;
  }

  public LoanCosts deepCopy() {
    return new LoanCosts(this);
  }

  @Override
  public void clear() {
    setCurrencyCostIsSet(false);
    this.currencyCost = 0.0;
  }

  public double getCurrencyCost() {
    return this.currencyCost;
  }

  public LoanCosts setCurrencyCost(double currencyCost) {
    this.currencyCost = currencyCost;
    setCurrencyCostIsSet(true);
    return this;
  }

  public void unsetCurrencyCost() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __CURRENCYCOST_ISSET_ID);
  }

  /** Returns true if field currencyCost is set (has been assigned a value) and false otherwise */
  public boolean isSetCurrencyCost() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __CURRENCYCOST_ISSET_ID);
  }

  public void setCurrencyCostIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __CURRENCYCOST_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, java.lang.Object value) {
    switch (field) {
    case CURRENCY_COST:
      if (value == null) {
        unsetCurrencyCost();
      } else {
        setCurrencyCost((java.lang.Double)value);
      }
      break;

    }
  }

  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case CURRENCY_COST:
      return getCurrencyCost();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case CURRENCY_COST:
      return isSetCurrencyCost();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof LoanCosts)
      return this.equals((LoanCosts)that);
    return false;
  }

  public boolean equals(LoanCosts that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_currencyCost = true;
    boolean that_present_currencyCost = true;
    if (this_present_currencyCost || that_present_currencyCost) {
      if (!(this_present_currencyCost && that_present_currencyCost))
        return false;
      if (this.currencyCost != that.currencyCost)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(currencyCost);

    return hashCode;
  }

  @Override
  public int compareTo(LoanCosts other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetCurrencyCost()).compareTo(other.isSetCurrencyCost());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCurrencyCost()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.currencyCost, other.currencyCost);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("LoanCosts(");
    boolean first = true;

    sb.append("currencyCost:");
    sb.append(this.currencyCost);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class LoanCostsStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public LoanCostsStandardScheme getScheme() {
      return new LoanCostsStandardScheme();
    }
  }

  private static class LoanCostsStandardScheme extends org.apache.thrift.scheme.StandardScheme<LoanCosts> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, LoanCosts struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // CURRENCY_COST
            if (schemeField.type == org.apache.thrift.protocol.TType.DOUBLE) {
              struct.currencyCost = iprot.readDouble();
              struct.setCurrencyCostIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, LoanCosts struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(CURRENCY_COST_FIELD_DESC);
      oprot.writeDouble(struct.currencyCost);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class LoanCostsTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public LoanCostsTupleScheme getScheme() {
      return new LoanCostsTupleScheme();
    }
  }

  private static class LoanCostsTupleScheme extends org.apache.thrift.scheme.TupleScheme<LoanCosts> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, LoanCosts struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetCurrencyCost()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetCurrencyCost()) {
        oprot.writeDouble(struct.currencyCost);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, LoanCosts struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        struct.currencyCost = iprot.readDouble();
        struct.setCurrencyCostIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

