/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package bank;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.11.0)", date = "2018-07-01")
public class PremiumAccountService {

  public interface Iface extends AccountService.Iface {

    public LoanCosts getLoanDetails(java.lang.String guid, LoanParameters loanParameters) throws AuthorizationException, InvalidArgumentException, org.apache.thrift.TException;

  }

  public interface AsyncIface extends AccountService .AsyncIface {

    public void getLoanDetails(java.lang.String guid, LoanParameters loanParameters, org.apache.thrift.async.AsyncMethodCallback<LoanCosts> resultHandler) throws org.apache.thrift.TException;

  }

  public static class Client extends AccountService.Client implements Iface {
    public static class Factory implements org.apache.thrift.TServiceClientFactory<Client> {
      public Factory() {}
      public Client getClient(org.apache.thrift.protocol.TProtocol prot) {
        return new Client(prot);
      }
      public Client getClient(org.apache.thrift.protocol.TProtocol iprot, org.apache.thrift.protocol.TProtocol oprot) {
        return new Client(iprot, oprot);
      }
    }

    public Client(org.apache.thrift.protocol.TProtocol prot)
    {
      super(prot, prot);
    }

    public Client(org.apache.thrift.protocol.TProtocol iprot, org.apache.thrift.protocol.TProtocol oprot) {
      super(iprot, oprot);
    }

    public LoanCosts getLoanDetails(java.lang.String guid, LoanParameters loanParameters) throws AuthorizationException, InvalidArgumentException, org.apache.thrift.TException
    {
      send_getLoanDetails(guid, loanParameters);
      return recv_getLoanDetails();
    }

    public void send_getLoanDetails(java.lang.String guid, LoanParameters loanParameters) throws org.apache.thrift.TException
    {
      getLoanDetails_args args = new getLoanDetails_args();
      args.setGuid(guid);
      args.setLoanParameters(loanParameters);
      sendBase("getLoanDetails", args);
    }

    public LoanCosts recv_getLoanDetails() throws AuthorizationException, InvalidArgumentException, org.apache.thrift.TException
    {
      getLoanDetails_result result = new getLoanDetails_result();
      receiveBase(result, "getLoanDetails");
      if (result.isSetSuccess()) {
        return result.success;
      }
      if (result.authorizationException != null) {
        throw result.authorizationException;
      }
      if (result.invalidArgumentException != null) {
        throw result.invalidArgumentException;
      }
      throw new org.apache.thrift.TApplicationException(org.apache.thrift.TApplicationException.MISSING_RESULT, "getLoanDetails failed: unknown result");
    }

  }
  public static class AsyncClient extends AccountService.AsyncClient implements AsyncIface {
    public static class Factory implements org.apache.thrift.async.TAsyncClientFactory<AsyncClient> {
      private org.apache.thrift.async.TAsyncClientManager clientManager;
      private org.apache.thrift.protocol.TProtocolFactory protocolFactory;
      public Factory(org.apache.thrift.async.TAsyncClientManager clientManager, org.apache.thrift.protocol.TProtocolFactory protocolFactory) {
        this.clientManager = clientManager;
        this.protocolFactory = protocolFactory;
      }
      public AsyncClient getAsyncClient(org.apache.thrift.transport.TNonblockingTransport transport) {
        return new AsyncClient(protocolFactory, clientManager, transport);
      }
    }

    public AsyncClient(org.apache.thrift.protocol.TProtocolFactory protocolFactory, org.apache.thrift.async.TAsyncClientManager clientManager, org.apache.thrift.transport.TNonblockingTransport transport) {
      super(protocolFactory, clientManager, transport);
    }

    public void getLoanDetails(java.lang.String guid, LoanParameters loanParameters, org.apache.thrift.async.AsyncMethodCallback<LoanCosts> resultHandler) throws org.apache.thrift.TException {
      checkReady();
      getLoanDetails_call method_call = new getLoanDetails_call(guid, loanParameters, resultHandler, this, ___protocolFactory, ___transport);
      this.___currentMethod = method_call;
      ___manager.call(method_call);
    }

    public static class getLoanDetails_call extends org.apache.thrift.async.TAsyncMethodCall<LoanCosts> {
      private java.lang.String guid;
      private LoanParameters loanParameters;
      public getLoanDetails_call(java.lang.String guid, LoanParameters loanParameters, org.apache.thrift.async.AsyncMethodCallback<LoanCosts> resultHandler, org.apache.thrift.async.TAsyncClient client, org.apache.thrift.protocol.TProtocolFactory protocolFactory, org.apache.thrift.transport.TNonblockingTransport transport) throws org.apache.thrift.TException {
        super(client, protocolFactory, transport, resultHandler, false);
        this.guid = guid;
        this.loanParameters = loanParameters;
      }

      public void write_args(org.apache.thrift.protocol.TProtocol prot) throws org.apache.thrift.TException {
        prot.writeMessageBegin(new org.apache.thrift.protocol.TMessage("getLoanDetails", org.apache.thrift.protocol.TMessageType.CALL, 0));
        getLoanDetails_args args = new getLoanDetails_args();
        args.setGuid(guid);
        args.setLoanParameters(loanParameters);
        args.write(prot);
        prot.writeMessageEnd();
      }

      public LoanCosts getResult() throws AuthorizationException, InvalidArgumentException, org.apache.thrift.TException {
        if (getState() != org.apache.thrift.async.TAsyncMethodCall.State.RESPONSE_READ) {
          throw new java.lang.IllegalStateException("Method call not finished!");
        }
        org.apache.thrift.transport.TMemoryInputTransport memoryTransport = new org.apache.thrift.transport.TMemoryInputTransport(getFrameBuffer().array());
        org.apache.thrift.protocol.TProtocol prot = client.getProtocolFactory().getProtocol(memoryTransport);
        return (new Client(prot)).recv_getLoanDetails();
      }
    }

  }

  public static class Processor<I extends Iface> extends AccountService.Processor<I> implements org.apache.thrift.TProcessor {
    private static final org.slf4j.Logger _LOGGER = org.slf4j.LoggerFactory.getLogger(Processor.class.getName());
    public Processor(I iface) {
      super(iface, getProcessMap(new java.util.HashMap<java.lang.String, org.apache.thrift.ProcessFunction<I, ? extends org.apache.thrift.TBase>>()));
    }

    protected Processor(I iface, java.util.Map<java.lang.String, org.apache.thrift.ProcessFunction<I, ? extends org.apache.thrift.TBase>> processMap) {
      super(iface, getProcessMap(processMap));
    }

    private static <I extends Iface> java.util.Map<java.lang.String,  org.apache.thrift.ProcessFunction<I, ? extends org.apache.thrift.TBase>> getProcessMap(java.util.Map<java.lang.String, org.apache.thrift.ProcessFunction<I, ? extends  org.apache.thrift.TBase>> processMap) {
      processMap.put("getLoanDetails", new getLoanDetails());
      return processMap;
    }

    public static class getLoanDetails<I extends Iface> extends org.apache.thrift.ProcessFunction<I, getLoanDetails_args> {
      public getLoanDetails() {
        super("getLoanDetails");
      }

      public getLoanDetails_args getEmptyArgsInstance() {
        return new getLoanDetails_args();
      }

      protected boolean isOneway() {
        return false;
      }

      @Override
      protected boolean handleRuntimeExceptions() {
        return false;
      }

      public getLoanDetails_result getResult(I iface, getLoanDetails_args args) throws org.apache.thrift.TException {
        getLoanDetails_result result = new getLoanDetails_result();
        try {
          result.success = iface.getLoanDetails(args.guid, args.loanParameters);
        } catch (AuthorizationException authorizationException) {
          result.authorizationException = authorizationException;
        } catch (InvalidArgumentException invalidArgumentException) {
          result.invalidArgumentException = invalidArgumentException;
        }
        return result;
      }
    }

  }

  public static class AsyncProcessor<I extends AsyncIface> extends AccountService.AsyncProcessor<I> {
    private static final org.slf4j.Logger _LOGGER = org.slf4j.LoggerFactory.getLogger(AsyncProcessor.class.getName());
    public AsyncProcessor(I iface) {
      super(iface, getProcessMap(new java.util.HashMap<java.lang.String, org.apache.thrift.AsyncProcessFunction<I, ? extends org.apache.thrift.TBase, ?>>()));
    }

    protected AsyncProcessor(I iface, java.util.Map<java.lang.String,  org.apache.thrift.AsyncProcessFunction<I, ? extends  org.apache.thrift.TBase, ?>> processMap) {
      super(iface, getProcessMap(processMap));
    }

    private static <I extends AsyncIface> java.util.Map<java.lang.String,  org.apache.thrift.AsyncProcessFunction<I, ? extends  org.apache.thrift.TBase,?>> getProcessMap(java.util.Map<java.lang.String,  org.apache.thrift.AsyncProcessFunction<I, ? extends  org.apache.thrift.TBase, ?>> processMap) {
      processMap.put("getLoanDetails", new getLoanDetails());
      return processMap;
    }

    public static class getLoanDetails<I extends AsyncIface> extends org.apache.thrift.AsyncProcessFunction<I, getLoanDetails_args, LoanCosts> {
      public getLoanDetails() {
        super("getLoanDetails");
      }

      public getLoanDetails_args getEmptyArgsInstance() {
        return new getLoanDetails_args();
      }

      public org.apache.thrift.async.AsyncMethodCallback<LoanCosts> getResultHandler(final org.apache.thrift.server.AbstractNonblockingServer.AsyncFrameBuffer fb, final int seqid) {
        final org.apache.thrift.AsyncProcessFunction fcall = this;
        return new org.apache.thrift.async.AsyncMethodCallback<LoanCosts>() { 
          public void onComplete(LoanCosts o) {
            getLoanDetails_result result = new getLoanDetails_result();
            result.success = o;
            try {
              fcall.sendResponse(fb, result, org.apache.thrift.protocol.TMessageType.REPLY,seqid);
            } catch (org.apache.thrift.transport.TTransportException e) {
              _LOGGER.error("TTransportException writing to internal frame buffer", e);
              fb.close();
            } catch (java.lang.Exception e) {
              _LOGGER.error("Exception writing to internal frame buffer", e);
              onError(e);
            }
          }
          public void onError(java.lang.Exception e) {
            byte msgType = org.apache.thrift.protocol.TMessageType.REPLY;
            org.apache.thrift.TSerializable msg;
            getLoanDetails_result result = new getLoanDetails_result();
            if (e instanceof AuthorizationException) {
              result.authorizationException = (AuthorizationException) e;
              result.setAuthorizationExceptionIsSet(true);
              msg = result;
            } else if (e instanceof InvalidArgumentException) {
              result.invalidArgumentException = (InvalidArgumentException) e;
              result.setInvalidArgumentExceptionIsSet(true);
              msg = result;
            } else if (e instanceof org.apache.thrift.transport.TTransportException) {
              _LOGGER.error("TTransportException inside handler", e);
              fb.close();
              return;
            } else if (e instanceof org.apache.thrift.TApplicationException) {
              _LOGGER.error("TApplicationException inside handler", e);
              msgType = org.apache.thrift.protocol.TMessageType.EXCEPTION;
              msg = (org.apache.thrift.TApplicationException)e;
            } else {
              _LOGGER.error("Exception inside handler", e);
              msgType = org.apache.thrift.protocol.TMessageType.EXCEPTION;
              msg = new org.apache.thrift.TApplicationException(org.apache.thrift.TApplicationException.INTERNAL_ERROR, e.getMessage());
            }
            try {
              fcall.sendResponse(fb,msg,msgType,seqid);
            } catch (java.lang.Exception ex) {
              _LOGGER.error("Exception writing to internal frame buffer", ex);
              fb.close();
            }
          }
        };
      }

      protected boolean isOneway() {
        return false;
      }

      public void start(I iface, getLoanDetails_args args, org.apache.thrift.async.AsyncMethodCallback<LoanCosts> resultHandler) throws org.apache.thrift.TException {
        iface.getLoanDetails(args.guid, args.loanParameters,resultHandler);
      }
    }

  }

  public static class getLoanDetails_args implements org.apache.thrift.TBase<getLoanDetails_args, getLoanDetails_args._Fields>, java.io.Serializable, Cloneable, Comparable<getLoanDetails_args>   {
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("getLoanDetails_args");

    private static final org.apache.thrift.protocol.TField GUID_FIELD_DESC = new org.apache.thrift.protocol.TField("guid", org.apache.thrift.protocol.TType.STRING, (short)1);
    private static final org.apache.thrift.protocol.TField LOAN_PARAMETERS_FIELD_DESC = new org.apache.thrift.protocol.TField("loanParameters", org.apache.thrift.protocol.TType.STRUCT, (short)2);

    private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new getLoanDetails_argsStandardSchemeFactory();
    private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new getLoanDetails_argsTupleSchemeFactory();

    public java.lang.String guid; // required
    public LoanParameters loanParameters; // required

    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
      GUID((short)1, "guid"),
      LOAN_PARAMETERS((short)2, "loanParameters");

      private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

      static {
        for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
          byName.put(field.getFieldName(), field);
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, or null if its not found.
       */
      public static _Fields findByThriftId(int fieldId) {
        switch(fieldId) {
          case 1: // GUID
            return GUID;
          case 2: // LOAN_PARAMETERS
            return LOAN_PARAMETERS;
          default:
            return null;
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, throwing an exception
       * if it is not found.
       */
      public static _Fields findByThriftIdOrThrow(int fieldId) {
        _Fields fields = findByThriftId(fieldId);
        if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
        return fields;
      }

      /**
       * Find the _Fields constant that matches name, or null if its not found.
       */
      public static _Fields findByName(java.lang.String name) {
        return byName.get(name);
      }

      private final short _thriftId;
      private final java.lang.String _fieldName;

      _Fields(short thriftId, java.lang.String fieldName) {
        _thriftId = thriftId;
        _fieldName = fieldName;
      }

      public short getThriftFieldId() {
        return _thriftId;
      }

      public java.lang.String getFieldName() {
        return _fieldName;
      }
    }

    // isset id assignments
    public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
    static {
      java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
      tmpMap.put(_Fields.GUID, new org.apache.thrift.meta_data.FieldMetaData("guid", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING          , "GUID")));
      tmpMap.put(_Fields.LOAN_PARAMETERS, new org.apache.thrift.meta_data.FieldMetaData("loanParameters", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, LoanParameters.class)));
      metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
      org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(getLoanDetails_args.class, metaDataMap);
    }

    public getLoanDetails_args() {
    }

    public getLoanDetails_args(
      java.lang.String guid,
      LoanParameters loanParameters)
    {
      this();
      this.guid = guid;
      this.loanParameters = loanParameters;
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public getLoanDetails_args(getLoanDetails_args other) {
      if (other.isSetGuid()) {
        this.guid = other.guid;
      }
      if (other.isSetLoanParameters()) {
        this.loanParameters = new LoanParameters(other.loanParameters);
      }
    }

    public getLoanDetails_args deepCopy() {
      return new getLoanDetails_args(this);
    }

    @Override
    public void clear() {
      this.guid = null;
      this.loanParameters = null;
    }

    public java.lang.String getGuid() {
      return this.guid;
    }

    public getLoanDetails_args setGuid(java.lang.String guid) {
      this.guid = guid;
      return this;
    }

    public void unsetGuid() {
      this.guid = null;
    }

    /** Returns true if field guid is set (has been assigned a value) and false otherwise */
    public boolean isSetGuid() {
      return this.guid != null;
    }

    public void setGuidIsSet(boolean value) {
      if (!value) {
        this.guid = null;
      }
    }

    public LoanParameters getLoanParameters() {
      return this.loanParameters;
    }

    public getLoanDetails_args setLoanParameters(LoanParameters loanParameters) {
      this.loanParameters = loanParameters;
      return this;
    }

    public void unsetLoanParameters() {
      this.loanParameters = null;
    }

    /** Returns true if field loanParameters is set (has been assigned a value) and false otherwise */
    public boolean isSetLoanParameters() {
      return this.loanParameters != null;
    }

    public void setLoanParametersIsSet(boolean value) {
      if (!value) {
        this.loanParameters = null;
      }
    }

    public void setFieldValue(_Fields field, java.lang.Object value) {
      switch (field) {
      case GUID:
        if (value == null) {
          unsetGuid();
        } else {
          setGuid((java.lang.String)value);
        }
        break;

      case LOAN_PARAMETERS:
        if (value == null) {
          unsetLoanParameters();
        } else {
          setLoanParameters((LoanParameters)value);
        }
        break;

      }
    }

    public java.lang.Object getFieldValue(_Fields field) {
      switch (field) {
      case GUID:
        return getGuid();

      case LOAN_PARAMETERS:
        return getLoanParameters();

      }
      throw new java.lang.IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    public boolean isSet(_Fields field) {
      if (field == null) {
        throw new java.lang.IllegalArgumentException();
      }

      switch (field) {
      case GUID:
        return isSetGuid();
      case LOAN_PARAMETERS:
        return isSetLoanParameters();
      }
      throw new java.lang.IllegalStateException();
    }

    @Override
    public boolean equals(java.lang.Object that) {
      if (that == null)
        return false;
      if (that instanceof getLoanDetails_args)
        return this.equals((getLoanDetails_args)that);
      return false;
    }

    public boolean equals(getLoanDetails_args that) {
      if (that == null)
        return false;
      if (this == that)
        return true;

      boolean this_present_guid = true && this.isSetGuid();
      boolean that_present_guid = true && that.isSetGuid();
      if (this_present_guid || that_present_guid) {
        if (!(this_present_guid && that_present_guid))
          return false;
        if (!this.guid.equals(that.guid))
          return false;
      }

      boolean this_present_loanParameters = true && this.isSetLoanParameters();
      boolean that_present_loanParameters = true && that.isSetLoanParameters();
      if (this_present_loanParameters || that_present_loanParameters) {
        if (!(this_present_loanParameters && that_present_loanParameters))
          return false;
        if (!this.loanParameters.equals(that.loanParameters))
          return false;
      }

      return true;
    }

    @Override
    public int hashCode() {
      int hashCode = 1;

      hashCode = hashCode * 8191 + ((isSetGuid()) ? 131071 : 524287);
      if (isSetGuid())
        hashCode = hashCode * 8191 + guid.hashCode();

      hashCode = hashCode * 8191 + ((isSetLoanParameters()) ? 131071 : 524287);
      if (isSetLoanParameters())
        hashCode = hashCode * 8191 + loanParameters.hashCode();

      return hashCode;
    }

    @Override
    public int compareTo(getLoanDetails_args other) {
      if (!getClass().equals(other.getClass())) {
        return getClass().getName().compareTo(other.getClass().getName());
      }

      int lastComparison = 0;

      lastComparison = java.lang.Boolean.valueOf(isSetGuid()).compareTo(other.isSetGuid());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetGuid()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.guid, other.guid);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      lastComparison = java.lang.Boolean.valueOf(isSetLoanParameters()).compareTo(other.isSetLoanParameters());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetLoanParameters()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.loanParameters, other.loanParameters);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      return 0;
    }

    public _Fields fieldForId(int fieldId) {
      return _Fields.findByThriftId(fieldId);
    }

    public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
      scheme(iprot).read(iprot, this);
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
      scheme(oprot).write(oprot, this);
    }

    @Override
    public java.lang.String toString() {
      java.lang.StringBuilder sb = new java.lang.StringBuilder("getLoanDetails_args(");
      boolean first = true;

      sb.append("guid:");
      if (this.guid == null) {
        sb.append("null");
      } else {
        sb.append(this.guid);
      }
      first = false;
      if (!first) sb.append(", ");
      sb.append("loanParameters:");
      if (this.loanParameters == null) {
        sb.append("null");
      } else {
        sb.append(this.loanParameters);
      }
      first = false;
      sb.append(")");
      return sb.toString();
    }

    public void validate() throws org.apache.thrift.TException {
      // check for required fields
      // check for sub-struct validity
      if (loanParameters != null) {
        loanParameters.validate();
      }
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
      try {
        write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
      try {
        read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private static class getLoanDetails_argsStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
      public getLoanDetails_argsStandardScheme getScheme() {
        return new getLoanDetails_argsStandardScheme();
      }
    }

    private static class getLoanDetails_argsStandardScheme extends org.apache.thrift.scheme.StandardScheme<getLoanDetails_args> {

      public void read(org.apache.thrift.protocol.TProtocol iprot, getLoanDetails_args struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TField schemeField;
        iprot.readStructBegin();
        while (true)
        {
          schemeField = iprot.readFieldBegin();
          if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
            break;
          }
          switch (schemeField.id) {
            case 1: // GUID
              if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
                struct.guid = iprot.readString();
                struct.setGuidIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            case 2: // LOAN_PARAMETERS
              if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
                struct.loanParameters = new LoanParameters();
                struct.loanParameters.read(iprot);
                struct.setLoanParametersIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            default:
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
          }
          iprot.readFieldEnd();
        }
        iprot.readStructEnd();

        // check for required fields of primitive type, which can't be checked in the validate method
        struct.validate();
      }

      public void write(org.apache.thrift.protocol.TProtocol oprot, getLoanDetails_args struct) throws org.apache.thrift.TException {
        struct.validate();

        oprot.writeStructBegin(STRUCT_DESC);
        if (struct.guid != null) {
          oprot.writeFieldBegin(GUID_FIELD_DESC);
          oprot.writeString(struct.guid);
          oprot.writeFieldEnd();
        }
        if (struct.loanParameters != null) {
          oprot.writeFieldBegin(LOAN_PARAMETERS_FIELD_DESC);
          struct.loanParameters.write(oprot);
          oprot.writeFieldEnd();
        }
        oprot.writeFieldStop();
        oprot.writeStructEnd();
      }

    }

    private static class getLoanDetails_argsTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
      public getLoanDetails_argsTupleScheme getScheme() {
        return new getLoanDetails_argsTupleScheme();
      }
    }

    private static class getLoanDetails_argsTupleScheme extends org.apache.thrift.scheme.TupleScheme<getLoanDetails_args> {

      @Override
      public void write(org.apache.thrift.protocol.TProtocol prot, getLoanDetails_args struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
        java.util.BitSet optionals = new java.util.BitSet();
        if (struct.isSetGuid()) {
          optionals.set(0);
        }
        if (struct.isSetLoanParameters()) {
          optionals.set(1);
        }
        oprot.writeBitSet(optionals, 2);
        if (struct.isSetGuid()) {
          oprot.writeString(struct.guid);
        }
        if (struct.isSetLoanParameters()) {
          struct.loanParameters.write(oprot);
        }
      }

      @Override
      public void read(org.apache.thrift.protocol.TProtocol prot, getLoanDetails_args struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
        java.util.BitSet incoming = iprot.readBitSet(2);
        if (incoming.get(0)) {
          struct.guid = iprot.readString();
          struct.setGuidIsSet(true);
        }
        if (incoming.get(1)) {
          struct.loanParameters = new LoanParameters();
          struct.loanParameters.read(iprot);
          struct.setLoanParametersIsSet(true);
        }
      }
    }

    private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
      return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
    }
  }

  public static class getLoanDetails_result implements org.apache.thrift.TBase<getLoanDetails_result, getLoanDetails_result._Fields>, java.io.Serializable, Cloneable, Comparable<getLoanDetails_result>   {
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("getLoanDetails_result");

    private static final org.apache.thrift.protocol.TField SUCCESS_FIELD_DESC = new org.apache.thrift.protocol.TField("success", org.apache.thrift.protocol.TType.STRUCT, (short)0);
    private static final org.apache.thrift.protocol.TField AUTHORIZATION_EXCEPTION_FIELD_DESC = new org.apache.thrift.protocol.TField("authorizationException", org.apache.thrift.protocol.TType.STRUCT, (short)1);
    private static final org.apache.thrift.protocol.TField INVALID_ARGUMENT_EXCEPTION_FIELD_DESC = new org.apache.thrift.protocol.TField("invalidArgumentException", org.apache.thrift.protocol.TType.STRUCT, (short)2);

    private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new getLoanDetails_resultStandardSchemeFactory();
    private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new getLoanDetails_resultTupleSchemeFactory();

    public LoanCosts success; // required
    public AuthorizationException authorizationException; // required
    public InvalidArgumentException invalidArgumentException; // required

    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
      SUCCESS((short)0, "success"),
      AUTHORIZATION_EXCEPTION((short)1, "authorizationException"),
      INVALID_ARGUMENT_EXCEPTION((short)2, "invalidArgumentException");

      private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

      static {
        for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
          byName.put(field.getFieldName(), field);
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, or null if its not found.
       */
      public static _Fields findByThriftId(int fieldId) {
        switch(fieldId) {
          case 0: // SUCCESS
            return SUCCESS;
          case 1: // AUTHORIZATION_EXCEPTION
            return AUTHORIZATION_EXCEPTION;
          case 2: // INVALID_ARGUMENT_EXCEPTION
            return INVALID_ARGUMENT_EXCEPTION;
          default:
            return null;
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, throwing an exception
       * if it is not found.
       */
      public static _Fields findByThriftIdOrThrow(int fieldId) {
        _Fields fields = findByThriftId(fieldId);
        if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
        return fields;
      }

      /**
       * Find the _Fields constant that matches name, or null if its not found.
       */
      public static _Fields findByName(java.lang.String name) {
        return byName.get(name);
      }

      private final short _thriftId;
      private final java.lang.String _fieldName;

      _Fields(short thriftId, java.lang.String fieldName) {
        _thriftId = thriftId;
        _fieldName = fieldName;
      }

      public short getThriftFieldId() {
        return _thriftId;
      }

      public java.lang.String getFieldName() {
        return _fieldName;
      }
    }

    // isset id assignments
    public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
    static {
      java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
      tmpMap.put(_Fields.SUCCESS, new org.apache.thrift.meta_data.FieldMetaData("success", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, LoanCosts.class)));
      tmpMap.put(_Fields.AUTHORIZATION_EXCEPTION, new org.apache.thrift.meta_data.FieldMetaData("authorizationException", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, AuthorizationException.class)));
      tmpMap.put(_Fields.INVALID_ARGUMENT_EXCEPTION, new org.apache.thrift.meta_data.FieldMetaData("invalidArgumentException", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, InvalidArgumentException.class)));
      metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
      org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(getLoanDetails_result.class, metaDataMap);
    }

    public getLoanDetails_result() {
    }

    public getLoanDetails_result(
      LoanCosts success,
      AuthorizationException authorizationException,
      InvalidArgumentException invalidArgumentException)
    {
      this();
      this.success = success;
      this.authorizationException = authorizationException;
      this.invalidArgumentException = invalidArgumentException;
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public getLoanDetails_result(getLoanDetails_result other) {
      if (other.isSetSuccess()) {
        this.success = new LoanCosts(other.success);
      }
      if (other.isSetAuthorizationException()) {
        this.authorizationException = new AuthorizationException(other.authorizationException);
      }
      if (other.isSetInvalidArgumentException()) {
        this.invalidArgumentException = new InvalidArgumentException(other.invalidArgumentException);
      }
    }

    public getLoanDetails_result deepCopy() {
      return new getLoanDetails_result(this);
    }

    @Override
    public void clear() {
      this.success = null;
      this.authorizationException = null;
      this.invalidArgumentException = null;
    }

    public LoanCosts getSuccess() {
      return this.success;
    }

    public getLoanDetails_result setSuccess(LoanCosts success) {
      this.success = success;
      return this;
    }

    public void unsetSuccess() {
      this.success = null;
    }

    /** Returns true if field success is set (has been assigned a value) and false otherwise */
    public boolean isSetSuccess() {
      return this.success != null;
    }

    public void setSuccessIsSet(boolean value) {
      if (!value) {
        this.success = null;
      }
    }

    public AuthorizationException getAuthorizationException() {
      return this.authorizationException;
    }

    public getLoanDetails_result setAuthorizationException(AuthorizationException authorizationException) {
      this.authorizationException = authorizationException;
      return this;
    }

    public void unsetAuthorizationException() {
      this.authorizationException = null;
    }

    /** Returns true if field authorizationException is set (has been assigned a value) and false otherwise */
    public boolean isSetAuthorizationException() {
      return this.authorizationException != null;
    }

    public void setAuthorizationExceptionIsSet(boolean value) {
      if (!value) {
        this.authorizationException = null;
      }
    }

    public InvalidArgumentException getInvalidArgumentException() {
      return this.invalidArgumentException;
    }

    public getLoanDetails_result setInvalidArgumentException(InvalidArgumentException invalidArgumentException) {
      this.invalidArgumentException = invalidArgumentException;
      return this;
    }

    public void unsetInvalidArgumentException() {
      this.invalidArgumentException = null;
    }

    /** Returns true if field invalidArgumentException is set (has been assigned a value) and false otherwise */
    public boolean isSetInvalidArgumentException() {
      return this.invalidArgumentException != null;
    }

    public void setInvalidArgumentExceptionIsSet(boolean value) {
      if (!value) {
        this.invalidArgumentException = null;
      }
    }

    public void setFieldValue(_Fields field, java.lang.Object value) {
      switch (field) {
      case SUCCESS:
        if (value == null) {
          unsetSuccess();
        } else {
          setSuccess((LoanCosts)value);
        }
        break;

      case AUTHORIZATION_EXCEPTION:
        if (value == null) {
          unsetAuthorizationException();
        } else {
          setAuthorizationException((AuthorizationException)value);
        }
        break;

      case INVALID_ARGUMENT_EXCEPTION:
        if (value == null) {
          unsetInvalidArgumentException();
        } else {
          setInvalidArgumentException((InvalidArgumentException)value);
        }
        break;

      }
    }

    public java.lang.Object getFieldValue(_Fields field) {
      switch (field) {
      case SUCCESS:
        return getSuccess();

      case AUTHORIZATION_EXCEPTION:
        return getAuthorizationException();

      case INVALID_ARGUMENT_EXCEPTION:
        return getInvalidArgumentException();

      }
      throw new java.lang.IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    public boolean isSet(_Fields field) {
      if (field == null) {
        throw new java.lang.IllegalArgumentException();
      }

      switch (field) {
      case SUCCESS:
        return isSetSuccess();
      case AUTHORIZATION_EXCEPTION:
        return isSetAuthorizationException();
      case INVALID_ARGUMENT_EXCEPTION:
        return isSetInvalidArgumentException();
      }
      throw new java.lang.IllegalStateException();
    }

    @Override
    public boolean equals(java.lang.Object that) {
      if (that == null)
        return false;
      if (that instanceof getLoanDetails_result)
        return this.equals((getLoanDetails_result)that);
      return false;
    }

    public boolean equals(getLoanDetails_result that) {
      if (that == null)
        return false;
      if (this == that)
        return true;

      boolean this_present_success = true && this.isSetSuccess();
      boolean that_present_success = true && that.isSetSuccess();
      if (this_present_success || that_present_success) {
        if (!(this_present_success && that_present_success))
          return false;
        if (!this.success.equals(that.success))
          return false;
      }

      boolean this_present_authorizationException = true && this.isSetAuthorizationException();
      boolean that_present_authorizationException = true && that.isSetAuthorizationException();
      if (this_present_authorizationException || that_present_authorizationException) {
        if (!(this_present_authorizationException && that_present_authorizationException))
          return false;
        if (!this.authorizationException.equals(that.authorizationException))
          return false;
      }

      boolean this_present_invalidArgumentException = true && this.isSetInvalidArgumentException();
      boolean that_present_invalidArgumentException = true && that.isSetInvalidArgumentException();
      if (this_present_invalidArgumentException || that_present_invalidArgumentException) {
        if (!(this_present_invalidArgumentException && that_present_invalidArgumentException))
          return false;
        if (!this.invalidArgumentException.equals(that.invalidArgumentException))
          return false;
      }

      return true;
    }

    @Override
    public int hashCode() {
      int hashCode = 1;

      hashCode = hashCode * 8191 + ((isSetSuccess()) ? 131071 : 524287);
      if (isSetSuccess())
        hashCode = hashCode * 8191 + success.hashCode();

      hashCode = hashCode * 8191 + ((isSetAuthorizationException()) ? 131071 : 524287);
      if (isSetAuthorizationException())
        hashCode = hashCode * 8191 + authorizationException.hashCode();

      hashCode = hashCode * 8191 + ((isSetInvalidArgumentException()) ? 131071 : 524287);
      if (isSetInvalidArgumentException())
        hashCode = hashCode * 8191 + invalidArgumentException.hashCode();

      return hashCode;
    }

    @Override
    public int compareTo(getLoanDetails_result other) {
      if (!getClass().equals(other.getClass())) {
        return getClass().getName().compareTo(other.getClass().getName());
      }

      int lastComparison = 0;

      lastComparison = java.lang.Boolean.valueOf(isSetSuccess()).compareTo(other.isSetSuccess());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetSuccess()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.success, other.success);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      lastComparison = java.lang.Boolean.valueOf(isSetAuthorizationException()).compareTo(other.isSetAuthorizationException());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetAuthorizationException()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.authorizationException, other.authorizationException);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      lastComparison = java.lang.Boolean.valueOf(isSetInvalidArgumentException()).compareTo(other.isSetInvalidArgumentException());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetInvalidArgumentException()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.invalidArgumentException, other.invalidArgumentException);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      return 0;
    }

    public _Fields fieldForId(int fieldId) {
      return _Fields.findByThriftId(fieldId);
    }

    public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
      scheme(iprot).read(iprot, this);
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
      scheme(oprot).write(oprot, this);
      }

    @Override
    public java.lang.String toString() {
      java.lang.StringBuilder sb = new java.lang.StringBuilder("getLoanDetails_result(");
      boolean first = true;

      sb.append("success:");
      if (this.success == null) {
        sb.append("null");
      } else {
        sb.append(this.success);
      }
      first = false;
      if (!first) sb.append(", ");
      sb.append("authorizationException:");
      if (this.authorizationException == null) {
        sb.append("null");
      } else {
        sb.append(this.authorizationException);
      }
      first = false;
      if (!first) sb.append(", ");
      sb.append("invalidArgumentException:");
      if (this.invalidArgumentException == null) {
        sb.append("null");
      } else {
        sb.append(this.invalidArgumentException);
      }
      first = false;
      sb.append(")");
      return sb.toString();
    }

    public void validate() throws org.apache.thrift.TException {
      // check for required fields
      // check for sub-struct validity
      if (success != null) {
        success.validate();
      }
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
      try {
        write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
      try {
        read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private static class getLoanDetails_resultStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
      public getLoanDetails_resultStandardScheme getScheme() {
        return new getLoanDetails_resultStandardScheme();
      }
    }

    private static class getLoanDetails_resultStandardScheme extends org.apache.thrift.scheme.StandardScheme<getLoanDetails_result> {

      public void read(org.apache.thrift.protocol.TProtocol iprot, getLoanDetails_result struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TField schemeField;
        iprot.readStructBegin();
        while (true)
        {
          schemeField = iprot.readFieldBegin();
          if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
            break;
          }
          switch (schemeField.id) {
            case 0: // SUCCESS
              if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
                struct.success = new LoanCosts();
                struct.success.read(iprot);
                struct.setSuccessIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            case 1: // AUTHORIZATION_EXCEPTION
              if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
                struct.authorizationException = new AuthorizationException();
                struct.authorizationException.read(iprot);
                struct.setAuthorizationExceptionIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            case 2: // INVALID_ARGUMENT_EXCEPTION
              if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
                struct.invalidArgumentException = new InvalidArgumentException();
                struct.invalidArgumentException.read(iprot);
                struct.setInvalidArgumentExceptionIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            default:
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
          }
          iprot.readFieldEnd();
        }
        iprot.readStructEnd();

        // check for required fields of primitive type, which can't be checked in the validate method
        struct.validate();
      }

      public void write(org.apache.thrift.protocol.TProtocol oprot, getLoanDetails_result struct) throws org.apache.thrift.TException {
        struct.validate();

        oprot.writeStructBegin(STRUCT_DESC);
        if (struct.success != null) {
          oprot.writeFieldBegin(SUCCESS_FIELD_DESC);
          struct.success.write(oprot);
          oprot.writeFieldEnd();
        }
        if (struct.authorizationException != null) {
          oprot.writeFieldBegin(AUTHORIZATION_EXCEPTION_FIELD_DESC);
          struct.authorizationException.write(oprot);
          oprot.writeFieldEnd();
        }
        if (struct.invalidArgumentException != null) {
          oprot.writeFieldBegin(INVALID_ARGUMENT_EXCEPTION_FIELD_DESC);
          struct.invalidArgumentException.write(oprot);
          oprot.writeFieldEnd();
        }
        oprot.writeFieldStop();
        oprot.writeStructEnd();
      }

    }

    private static class getLoanDetails_resultTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
      public getLoanDetails_resultTupleScheme getScheme() {
        return new getLoanDetails_resultTupleScheme();
      }
    }

    private static class getLoanDetails_resultTupleScheme extends org.apache.thrift.scheme.TupleScheme<getLoanDetails_result> {

      @Override
      public void write(org.apache.thrift.protocol.TProtocol prot, getLoanDetails_result struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
        java.util.BitSet optionals = new java.util.BitSet();
        if (struct.isSetSuccess()) {
          optionals.set(0);
        }
        if (struct.isSetAuthorizationException()) {
          optionals.set(1);
        }
        if (struct.isSetInvalidArgumentException()) {
          optionals.set(2);
        }
        oprot.writeBitSet(optionals, 3);
        if (struct.isSetSuccess()) {
          struct.success.write(oprot);
        }
        if (struct.isSetAuthorizationException()) {
          struct.authorizationException.write(oprot);
        }
        if (struct.isSetInvalidArgumentException()) {
          struct.invalidArgumentException.write(oprot);
        }
      }

      @Override
      public void read(org.apache.thrift.protocol.TProtocol prot, getLoanDetails_result struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
        java.util.BitSet incoming = iprot.readBitSet(3);
        if (incoming.get(0)) {
          struct.success = new LoanCosts();
          struct.success.read(iprot);
          struct.setSuccessIsSet(true);
        }
        if (incoming.get(1)) {
          struct.authorizationException = new AuthorizationException();
          struct.authorizationException.read(iprot);
          struct.setAuthorizationExceptionIsSet(true);
        }
        if (incoming.get(2)) {
          struct.invalidArgumentException = new InvalidArgumentException();
          struct.invalidArgumentException.read(iprot);
          struct.setInvalidArgumentExceptionIsSet(true);
        }
      }
    }

    private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
      return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
    }
  }

}
